[[redirects]]
    from = "/"
    to = "https://gsweats.notion.site/54CSH-16dc3d109c0f80abafc5e84987ae5f46"
    status = 302
    # force = true
    headers = { X-From = "Netlify 420-69" }


# [[edge_functions]]
# path = "/en/download/"
# function = "append-platform-slug"
#
